### ISSUE TITLE
Pandoc markdown engine support?

### ISSUE THREAD

**Issue by HaoZeke** [utatti/pen#17]
Is there any way of changing the markdown rendering engine to pandoc? I require it as I often use pmd specific features and then generate multiple outputs...

**Comment by utatti** [comment]
I will implement this with [simple-pandoc](https://github.com/utatti/simple-pandoc).

**Comment by utatti** [comment]
Implemented with `--pandoc` option.

```shell
# e.g.
pen --pandoc gfm README.md
```
